---
openapi: 3.0.1
info:
  title: BlogApp API V1 Docs
  description: This is a sample Blog application that allows users create and remove
    posts, comments and likes
  version: v1
paths:
  "/api/v1/users/{user_id}/posts/{post_id}/comments":
    get:
      summary: Retrieves a list of comments for a post
      tags:
      - Comments
      parameters:
      - name: user_id
        in: path
        description: The user's id that written the posts
        required: true
        schema:
          type: string
      - name: post_id
        in: path
        description: The post's id that has the comments
        required: true
        schema:
          type: string
      responses:
        '200':
          description: List of comments found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  users_id:
                    type: integer
                  posts_id:
                    type: integer
                  text:
                    type: string
                required:
                - id
                - user_id
                - post_id
                - text
    post:
      summary: Create a comment on a post
      tags:
      - Comment
      parameters:
      - name: user_id
        in: path
        description: The user's id that written the posts
        required: true
        schema:
          type: string
      - name: post_id
        in: path
        description: The post's id that has the comments
        required: true
        schema:
          type: string
      responses:
        '201':
          description: Comment created
        '422':
          description: Unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: string
        description: Content of the comment
  "/api/v1/users/{user_id}/posts":
    get:
      summary: Retrieves a list of posts
      tags:
      - Posts
      parameters:
      - name: user_id
        in: path
        description: The user's id that written the posts
        required: true
        schema:
          type: string
      responses:
        '200':
          description: List of posts found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  author_id_id:
                    type: integer
                  title:
                    type: string
                  text:
                    type: string
                  comments_counter:
                    type: integer
                  likes_counter:
                    type: integer
                required:
                - id
                - title
                - author_id_id
servers:
- url: http://localhost:3000/
  variables:
    defaultHost:
      default: localhost:3000
